Fix tests on PyPy3.
Previously they would fail like this:

  File /home/travis/build/zopefoundation/zope.schema/src/zope/schema/_bootstrapfields.py, line 522, in fromUnicode
    raise self._validation_error(*last_exc.args).with_field_and_value(self, value)
TypeError: __init__() missing 1 required positional argument: 'literal'